/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing18thdec_stage.wmstudio.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testing18thdec_stage.wmstudio.Many2oneCompChild2;

/**
 * Service object for domain model class {@link Many2oneCompChild2}.
 */
public interface Many2oneCompChild2Service {

    /**
     * Creates a new Many2oneCompChild2. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Many2oneCompChild2 if any.
     *
     * @param many2oneCompChild2 Details of the Many2oneCompChild2 to be created; value cannot be null.
     * @return The newly created Many2oneCompChild2.
     */
    Many2oneCompChild2 create(@Valid Many2oneCompChild2 many2oneCompChild2);


	/**
     * Returns Many2oneCompChild2 by given id if exists.
     *
     * @param many2onecompchild2Id The id of the Many2oneCompChild2 to get; value cannot be null.
     * @return Many2oneCompChild2 associated with the given many2onecompchild2Id.
	 * @throws EntityNotFoundException If no Many2oneCompChild2 is found.
     */
    Many2oneCompChild2 getById(Integer many2onecompchild2Id);

    /**
     * Find and return the Many2oneCompChild2 by given id if exists, returns null otherwise.
     *
     * @param many2onecompchild2Id The id of the Many2oneCompChild2 to get; value cannot be null.
     * @return Many2oneCompChild2 associated with the given many2onecompchild2Id.
     */
    Many2oneCompChild2 findById(Integer many2onecompchild2Id);

	/**
     * Find and return the list of Many2oneCompChild2s by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param many2onecompchild2Ids The id's of the Many2oneCompChild2 to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return Many2oneCompChild2s associated with the given many2onecompchild2Ids.
     */
    List<Many2oneCompChild2> findByMultipleIds(List<Integer> many2onecompchild2Ids, boolean orderedReturn);

    /**
     * Find and return the Many2oneCompChild2 for given child2ByteId  andchild2CharId  andchild2DoubleId  if exists.
     *
     * @param child2ByteId value of child2ByteId; value cannot be null.
     * @param child2CharId value of child2CharId; value cannot be null.
     * @param child2DoubleId value of child2DoubleId; value cannot be null.
     * @return Many2oneCompChild2 associated with the given inputs.
     * @throws EntityNotFoundException if no matching Many2oneCompChild2 found.
     */
    Many2oneCompChild2 getByChild2ByteIdAndChild2CharIdAndChild2DoubleId(Byte child2ByteId, String child2CharId, BigDecimal child2DoubleId);

    /**
     * Updates the details of an existing Many2oneCompChild2. It replaces all fields of the existing Many2oneCompChild2 with the given many2oneCompChild2.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Many2oneCompChild2 if any.
     *
     * @param many2oneCompChild2 The details of the Many2oneCompChild2 to be updated; value cannot be null.
     * @return The updated Many2oneCompChild2.
     * @throws EntityNotFoundException if no Many2oneCompChild2 is found with given input.
     */
    Many2oneCompChild2 update(@Valid Many2oneCompChild2 many2oneCompChild2);


    /**
     * Partially updates the details of an existing Many2oneCompChild2. It updates only the
     * fields of the existing Many2oneCompChild2 which are passed in the many2oneCompChild2Patch.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Many2oneCompChild2 if any.
     *
     * @param many2onecompchild2Id The id of the Many2oneCompChild2 to be deleted; value cannot be null.
     * @param many2oneCompChild2Patch The partial data of Many2oneCompChild2 which is supposed to be updated; value cannot be null.
     * @return The updated Many2oneCompChild2.
     * @throws EntityNotFoundException if no Many2oneCompChild2 is found with given input.
     */
    Many2oneCompChild2 partialUpdate(Integer many2onecompchild2Id, Map<String, Object> many2oneCompChild2Patch);

    /**
     * Deletes an existing Many2oneCompChild2 with the given id.
     *
     * @param many2onecompchild2Id The id of the Many2oneCompChild2 to be deleted; value cannot be null.
     * @return The deleted Many2oneCompChild2.
     * @throws EntityNotFoundException if no Many2oneCompChild2 found with the given id.
     */
    Many2oneCompChild2 delete(Integer many2onecompchild2Id);

    /**
     * Deletes an existing Many2oneCompChild2 with the given object.
     *
     * @param many2oneCompChild2 The instance of the Many2oneCompChild2 to be deleted; value cannot be null.
     */
    void delete(Many2oneCompChild2 many2oneCompChild2);

    /**
     * Find all Many2oneCompChild2s matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Many2oneCompChild2s.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<Many2oneCompChild2> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all Many2oneCompChild2s matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Many2oneCompChild2s.
     *
     * @see Pageable
     * @see Page
     */
    Page<Many2oneCompChild2> findAll(String query, Pageable pageable);

    /**
     * Exports all Many2oneCompChild2s matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all Many2oneCompChild2s matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the Many2oneCompChild2s in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the Many2oneCompChild2.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}