/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing18thdec_stage.wmstudio.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.IOException;
import java.io.OutputStream;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.ObjectReader;
import com.wavemaker.commons.InvalidInputException;
import com.wavemaker.commons.MessageResource;
import com.wavemaker.runtime.data.annotations.EntityService;
import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testing18thdec_stage.wmstudio.One2oneUcChild;
import com.testing18thdec_stage.wmstudio.One2oneUcChild1;


/**
 * ServiceImpl object for domain model class One2oneUcChild1.
 *
 * @see One2oneUcChild1
 */
@Service("WMSTUDIO.One2oneUcChild1Service")
@Validated
@EntityService(entityClass = One2oneUcChild1.class, serviceId = "WMSTUDIO")
public class One2oneUcChild1ServiceImpl implements One2oneUcChild1Service {

    private static final Logger LOGGER = LoggerFactory.getLogger(One2oneUcChild1ServiceImpl.class);


    @Autowired
    @Qualifier("WMSTUDIO.One2oneUcChild1Dao")
    private WMGenericDao<One2oneUcChild1, Short> wmGenericDao;

    @Autowired
    @Qualifier("wmAppObjectMapper")
    private ObjectMapper objectMapper;


    public void setWMGenericDao(WMGenericDao<One2oneUcChild1, Short> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "WMSTUDIOTransactionManager")
    @Override
    public One2oneUcChild1 create(One2oneUcChild1 one2oneUcChild1) {
        LOGGER.debug("Creating a new One2oneUcChild1 with information: {}", one2oneUcChild1);

        One2oneUcChild1 one2oneUcChild1Created = this.wmGenericDao.create(one2oneUcChild1);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(one2oneUcChild1Created);
    }

    @Transactional(readOnly = true, value = "WMSTUDIOTransactionManager")
    @Override
    public One2oneUcChild1 getById(Short one2oneucchild1Id) {
        LOGGER.debug("Finding One2oneUcChild1 by id: {}", one2oneucchild1Id);
        return this.wmGenericDao.findById(one2oneucchild1Id);
    }

    @Transactional(readOnly = true, value = "WMSTUDIOTransactionManager")
    @Override
    public One2oneUcChild1 findById(Short one2oneucchild1Id) {
        LOGGER.debug("Finding One2oneUcChild1 by id: {}", one2oneucchild1Id);
        try {
            return this.wmGenericDao.findById(one2oneucchild1Id);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No One2oneUcChild1 found with id: {}", one2oneucchild1Id, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "WMSTUDIOTransactionManager")
    @Override
    public List<One2oneUcChild1> findByMultipleIds(List<Short> one2oneucchild1Ids, boolean orderedReturn) {
        LOGGER.debug("Finding One2oneUcChild1s by ids: {}", one2oneucchild1Ids);

        return this.wmGenericDao.findByMultipleIds(one2oneucchild1Ids, orderedReturn);
    }

    @Transactional(readOnly = true, value = "WMSTUDIOTransactionManager")
    @Override
    public One2oneUcChild1 getByEmailCol(String emailCol) {
        Map<String, Object> emailColMap = new HashMap<>();
        emailColMap.put("emailCol", emailCol);

        LOGGER.debug("Finding One2oneUcChild1 by unique keys: {}", emailColMap);
        return this.wmGenericDao.findByUniqueKey(emailColMap);
    }

    @Transactional(rollbackFor = EntityNotFoundException.class, value = "WMSTUDIOTransactionManager")
    @Override
    public One2oneUcChild1 update(One2oneUcChild1 one2oneUcChild1) {
        LOGGER.debug("Updating One2oneUcChild1 with information: {}", one2oneUcChild1);

        this.wmGenericDao.update(one2oneUcChild1);
        this.wmGenericDao.refresh(one2oneUcChild1);

        return one2oneUcChild1;
    }

    @Transactional(value = "WMSTUDIOTransactionManager")
    @Override
    public One2oneUcChild1 partialUpdate(Short one2oneucchild1Id, Map<String, Object>one2oneUcChild1Patch) {
        LOGGER.debug("Partially Updating the One2oneUcChild1 with id: {}", one2oneucchild1Id);

        One2oneUcChild1 one2oneUcChild1 = getById(one2oneucchild1Id);

        try {
            ObjectReader one2oneUcChild1Reader = this.objectMapper.reader().forType(One2oneUcChild1.class).withValueToUpdate(one2oneUcChild1);
            one2oneUcChild1 = one2oneUcChild1Reader.readValue(this.objectMapper.writeValueAsString(one2oneUcChild1Patch));
        } catch (IOException ex) {
            LOGGER.debug("There was a problem in applying the patch: {}", one2oneUcChild1Patch, ex);
            throw new InvalidInputException("Could not apply patch",ex);
        }

        one2oneUcChild1 = update(one2oneUcChild1);

        return one2oneUcChild1;
    }

    @Transactional(value = "WMSTUDIOTransactionManager")
    @Override
    public One2oneUcChild1 delete(Short one2oneucchild1Id) {
        LOGGER.debug("Deleting One2oneUcChild1 with id: {}", one2oneucchild1Id);
        One2oneUcChild1 deleted = this.wmGenericDao.findById(one2oneucchild1Id);
        if (deleted == null) {
            LOGGER.debug("No One2oneUcChild1 found with id: {}", one2oneucchild1Id);
            throw new EntityNotFoundException(MessageResource.create("com.wavemaker.runtime.entity.not.found"), One2oneUcChild1.class.getSimpleName(), one2oneucchild1Id);
        }
        // Removing references from parent Entities
        One2oneUcChild one2oneUcChildEntity = deleted.getOne2oneUcChild();
        if(one2oneUcChildEntity!=null) {
            one2oneUcChildEntity.setOne2oneUcChild1(null);
        }

        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "WMSTUDIOTransactionManager")
    @Override
    public void delete(One2oneUcChild1 one2oneUcChild1) {
        LOGGER.debug("Deleting One2oneUcChild1 with {}", one2oneUcChild1);
        this.wmGenericDao.delete(one2oneUcChild1);
    }

    @Transactional(readOnly = true, value = "WMSTUDIOTransactionManager")
    @Override
    public Page<One2oneUcChild1> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all One2oneUcChild1s");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "WMSTUDIOTransactionManager")
    @Override
    public Page<One2oneUcChild1> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all One2oneUcChild1s");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "WMSTUDIOTransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service WMSTUDIO for table One2oneUcChild1 to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "WMSTUDIOTransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service WMSTUDIO for table One2oneUcChild1 to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "WMSTUDIOTransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "WMSTUDIOTransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}