/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing18thdec_stage.wmstudio;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigInteger;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Countries generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`COUNTRIES`", schema = "HR")
public class Countries implements Serializable {

    private String countryId;
    private String countryName;
    private BigInteger regionId;

    @Id
    @Column(name = "`COUNTRY_ID`", nullable = false, length = 2)
    public String getCountryId() {
        return this.countryId;
    }

    public void setCountryId(String countryId) {
        this.countryId = countryId;
    }

    @Column(name = "`COUNTRY_NAME`", nullable = true, length = 40)
    public String getCountryName() {
        return this.countryName;
    }

    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

    @Column(name = "`REGION_ID`", nullable = true, scale = 0, precision = 38)
    public BigInteger getRegionId() {
        return this.regionId;
    }

    public void setRegionId(BigInteger regionId) {
        this.regionId = regionId;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Countries)) return false;
        final Countries countries = (Countries) o;
        return Objects.equals(getCountryId(), countries.getCountryId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCountryId());
    }
}

