/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing18thdec_stage.wmstudio;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

 
import java.time.LocalDateTime;

/**
 * One2oneVpkUcParent generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`ONE2ONE_VPK_UC_PARENT`", uniqueConstraints = {
        @UniqueConstraint(name = "`ONE2ONE_VPK_PARENT_UK1`", columnNames = {"`STRING_COL`"})})
@IdClass(One2oneVpkUcParentId.class)
public class One2oneVpkUcParent implements Serializable {

    private String stringCol;
     
    private LocalDateTime dateCol;
    private String charCol;
    private String clobCol;

    @Id
    @Column(name = "`STRING_COL`", nullable = true, length = 20)
    public String getStringCol() {
        return this.stringCol;
    }

    public void setStringCol(String stringCol) {
        this.stringCol = stringCol;
    }

    @Id
    @Column(name = "`DATE_COL`", nullable = true)
    public LocalDateTime getDateCol() {
        return this.dateCol;
    }

    public void setDateCol(LocalDateTime dateCol) {
        this.dateCol = dateCol;
    }

    @Id
    @Column(name = "`CHAR_COL`", nullable = true, length = 1)
    public String getCharCol() {
        return this.charCol;
    }

    public void setCharCol(String charCol) {
        this.charCol = charCol;
    }

    @Id
    @Column(name = "`CLOB_COL`", nullable = true, length = 4000)
    public String getClobCol() {
        return this.clobCol;
    }

    public void setClobCol(String clobCol) {
        this.clobCol = clobCol;
    }



    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof One2oneVpkUcParent)) return false;
        final One2oneVpkUcParent one2oneVpkUcParent = (One2oneVpkUcParent) o;
        return Objects.equals(getStringCol(), one2oneVpkUcParent.getStringCol()) &&
                Objects.equals(getDateCol(), one2oneVpkUcParent.getDateCol()) &&
                Objects.equals(getCharCol(), one2oneVpkUcParent.getCharCol()) &&
                Objects.equals(getClobCol(), one2oneVpkUcParent.getClobCol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getStringCol(),
                getDateCol(),
                getCharCol(),
                getClobCol());
    }
}

