/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing18thdec_stage.newtestdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

import org.hibernate.annotations.Type;
import org.joda.time.LocalDateTime;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

/**
 * DatabasedefinedTable generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`DATABASEDEFINED_TABLE`")
@IdClass(DatabasedefinedTableId.class)
public class DatabasedefinedTable implements Serializable {

    private Integer a;
    private Integer b;
    @Type(type = "DateTime")
    private LocalDateTime expires;
    @JsonProperty(access = Access.READ_ONLY)
    private byte[] x;
    private String column5;

    @Id
    @Column(name = "`a`", nullable = true, scale = 0, precision = 10)
    public Integer getA() {
        return this.a;
    }

    public void setA(Integer a) {
        this.a = a;
    }

    @Id
    @Column(name = "`b`", nullable = true, scale = 0, precision = 10)
    public Integer getB() {
        return this.b;
    }

    public void setB(Integer b) {
        this.b = b;
    }

    @Id
    @Column(name = "`expires`", nullable = true)
    public LocalDateTime getExpires() {
        return this.expires;
    }

    public void setExpires(LocalDateTime expires) {
        this.expires = expires;
    }

    @Id
    @Column(name = "`x`", nullable = true)
    public byte[] getX() {
        return this.x;
    }

    public void setX(byte[] x) {
        this.x = x;
    }

    @Id
    @Column(name = "`COLUMN5`", nullable = true, length = 255)
    public String getColumn5() {
        return this.column5;
    }

    public void setColumn5(String column5) {
        this.column5 = column5;
    }



    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof DatabasedefinedTable)) return false;
        final DatabasedefinedTable databasedefinedTable = (DatabasedefinedTable) o;
        return Objects.equals(getA(), databasedefinedTable.getA()) &&
                Objects.equals(getB(), databasedefinedTable.getB()) &&
                Objects.equals(getExpires(), databasedefinedTable.getExpires()) &&
                Objects.equals(getX(), databasedefinedTable.getX()) &&
                Objects.equals(getColumn5(), databasedefinedTable.getColumn5());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getA(),
                getB(),
                getExpires(),
                getX(),
                getColumn5());
    }
}

