/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing18thdec_stage.newtestdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * DbdefinedTimestamp generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`DBDEFINED_TIMESTAMP`")
@IdClass(DbdefinedTimestampId.class)
public class DbdefinedTimestamp implements Serializable {

    private Integer id;
    private Timestamp ts;
    private String column3;

    @Id
    @Column(name = "`id`", nullable = true, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Id
    @Column(name = "`ts`", nullable = true)
    public Timestamp getTs() {
        return this.ts;
    }

    public void setTs(Timestamp ts) {
        this.ts = ts;
    }

    @Id
    @Column(name = "`COLUMN3`", nullable = true, length = 255)
    public String getColumn3() {
        return this.column3;
    }

    public void setColumn3(String column3) {
        this.column3 = column3;
    }



    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof DbdefinedTimestamp)) return false;
        final DbdefinedTimestamp dbdefinedTimestamp = (DbdefinedTimestamp) o;
        return Objects.equals(getId(), dbdefinedTimestamp.getId()) &&
                Objects.equals(getTs(), dbdefinedTimestamp.getTs()) &&
                Objects.equals(getColumn3(), dbdefinedTimestamp.getColumn3());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getTs(),
                getColumn3());
    }
}

