/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing18thdec_stage.newtestdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;
import java.util.Objects;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

/**
 * Many2oneCompParent generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`Many2One_Comp_Parent`")
@IdClass(Many2oneCompParentId.class)
public class Many2oneCompParent implements Serializable {

    private Double floatId;
    private String charId;
    private String stringId;
    private BigDecimal doubleCol;
    @JsonProperty(access = Access.READ_ONLY)
    private byte[] blobCol;
    private Boolean booleanCol;
    private List<Many2oneCompChild> many2oneCompChilds;

    @Id
    @Column(name = "`FLOAT ID`", nullable = false, scale = 4, precision = 8)
    public Double getFloatId() {
        return this.floatId;
    }

    public void setFloatId(Double floatId) {
        this.floatId = floatId;
    }

    @Id
    @Column(name = "`CHAR ID`", nullable = false, length = 1)
    public String getCharId() {
        return this.charId;
    }

    public void setCharId(String charId) {
        this.charId = charId;
    }

    @Id
    @Column(name = "`STRING ID`", nullable = false, length = 50)
    public String getStringId() {
        return this.stringId;
    }

    public void setStringId(String stringId) {
        this.stringId = stringId;
    }

    @Id
    @Column(name = "`DOUBLE COL`", nullable = false, scale = 8, precision = 18)
    public BigDecimal getDoubleCol() {
        return this.doubleCol;
    }

    public void setDoubleCol(BigDecimal doubleCol) {
        this.doubleCol = doubleCol;
    }

    @Column(name = "`BLOB COL`", nullable = true)
    public byte[] getBlobCol() {
        return this.blobCol;
    }

    public void setBlobCol(byte[] blobCol) {
        this.blobCol = blobCol;
    }

    @Column(name = "`BOOLEAN COL`", nullable = true)
    public Boolean getBooleanCol() {
        return this.booleanCol;
    }

    public void setBooleanCol(Boolean booleanCol) {
        this.booleanCol = booleanCol;
    }

    @JsonInclude(Include.NON_EMPTY)
    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.REMOVE, mappedBy = "many2oneCompParent")
    public List<Many2oneCompChild> getMany2oneCompChilds() {
        return this.many2oneCompChilds;
    }

    public void setMany2oneCompChilds(List<Many2oneCompChild> many2oneCompChilds) {
        this.many2oneCompChilds = many2oneCompChilds;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Many2oneCompParent)) return false;
        final Many2oneCompParent many2oneCompParent = (Many2oneCompParent) o;
        return Objects.equals(getFloatId(), many2oneCompParent.getFloatId()) &&
                Objects.equals(getCharId(), many2oneCompParent.getCharId()) &&
                Objects.equals(getStringId(), many2oneCompParent.getStringId()) &&
                Objects.equals(getDoubleCol(), many2oneCompParent.getDoubleCol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getFloatId(),
                getCharId(),
                getStringId(),
                getDoubleCol());
    }
}

