/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing18thdec_stage.newtestdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

public class One2oneVirtualChildId implements Serializable {

    private String charId;
    private String stringCol;
    private Boolean booleanCol;
    private Date dateCol;

    public String getCharId() {
        return this.charId;
    }

    public void setCharId(String charId) {
        this.charId = charId;
    }

    public String getStringCol() {
        return this.stringCol;
    }

    public void setStringCol(String stringCol) {
        this.stringCol = stringCol;
    }

    public Boolean getBooleanCol() {
        return this.booleanCol;
    }

    public void setBooleanCol(Boolean booleanCol) {
        this.booleanCol = booleanCol;
    }

    public Date getDateCol() {
        return this.dateCol;
    }

    public void setDateCol(Date dateCol) {
        this.dateCol = dateCol;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof One2oneVirtualChild)) return false;
        final One2oneVirtualChild one2oneVirtualChild = (One2oneVirtualChild) o;
        return Objects.equals(getCharId(), one2oneVirtualChild.getCharId()) &&
                Objects.equals(getStringCol(), one2oneVirtualChild.getStringCol()) &&
                Objects.equals(getBooleanCol(), one2oneVirtualChild.getBooleanCol()) &&
                Objects.equals(getDateCol(), one2oneVirtualChild.getDateCol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCharId(),
                getStringCol(),
                getBooleanCol(),
                getDateCol());
    }
}
