/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing18thdec_stage.newtestdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * One2oneVirtualParent generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`One2One_Virtual_Parent`")
public class One2oneVirtualParent implements Serializable {

    private String charPkId;
    private Timestamp timestampCol;
    private Boolean booleanCol;

    @Id
    @Column(name = "`Char PK ID`", nullable = false, length = 1)
    public String getCharPkId() {
        return this.charPkId;
    }

    public void setCharPkId(String charPkId) {
        this.charPkId = charPkId;
    }

    @Column(name = "`TimestampCol`", nullable = true)
    public Timestamp getTimestampCol() {
        return this.timestampCol;
    }

    public void setTimestampCol(Timestamp timestampCol) {
        this.timestampCol = timestampCol;
    }

    @Column(name = "`Boolean Col`", nullable = true)
    public Boolean getBooleanCol() {
        return this.booleanCol;
    }

    public void setBooleanCol(Boolean booleanCol) {
        this.booleanCol = booleanCol;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof One2oneVirtualParent)) return false;
        final One2oneVirtualParent one2oneVirtualParent = (One2oneVirtualParent) o;
        return Objects.equals(getCharPkId(), one2oneVirtualParent.getCharPkId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCharPkId());
    }
}

