/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testing18thdec_stage.newtestdbpostgres.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.InputStream;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testing18thdec_stage.newtestdbpostgres.models.query.*;

public interface NewtestdbpostgresQueryExecutorService {

    SvGetSingleRecordResponse executeSV_GetSingleRecord(Integer pkId);

    InputStream getBlobColContentForSV_GetSingleRecord(Integer pkId) throws EntityNotFoundException;

    Page<SvAllTypesTableResponse> executeSV_AllTypesTable(Pageable pageable);

    InputStream getBlobColContentForSV_AllTypesTable(Integer pkId) throws EntityNotFoundException;

    Downloadable exportSV_AllTypesTable(ExportType exportType, Pageable pageable);

}


